# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [5]:
import numpy as np

In [6]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
# Printing the dimention of matrix A (number of axes)
print(A.ndim)

2


In [5]:
# Printing the shape of matrix A which the number of rows & columns
print(A.shape)

(3, 5)


In [6]:
# Printing the size of matrix A which shows the total number of elements in A
print(A.size)

15


In [7]:
# Printing the data type of matrix A
print(A.dtype)

int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [8]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [10]:
# Elementwise subtraction
D = B - C
D

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [11]:
# Elementwise multiplication (elementwise product)
E = B * C
E

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [12]:
# Matrix multiplication (matrix product)
F = B @ C
F

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [13]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# Exponentiate elemntwise
np.exp(B)


array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [19]:
# Calculate min value in whole matrix B
B.min()

1

In [20]:
# Calculate min value in each row of matrix B
B.min(axis=1)

array([1, 4, 7])

In [21]:
# Calculate min value in each column of matrix B
B.min(axis=0)

array([1, 2, 3])

In [23]:
# Finding index value for the min value in whole matrix B
B.argmin()

0

In [24]:
# Finding index value for the min value in each row of matrix B
B.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [37]:
# Calculate the sum for all elements of matrix B
B.sum()

45

In [45]:
# Calculate the mean for each column of Matrix B
np.mean(B, axis=0)

array([4., 5., 6.])

In [44]:
# Calculate the median for each column 
np.median(B, axis=0)

array([4., 5., 6.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [7]:

print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [47]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

Here we have a 2D array (3 rows & 5 columns). If we provide only one number (fewer indices than axes) when slicing, it is interprated as the row index. So, Numpy will return the entire row as the index. In this example it will return the second row, since index starts from 0: [ 6,  7,  8,  9, 10]. 

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [8]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [10]:
# If we would like to iterate through the array elementwise, we need to flatten the array first by flat attribute which is an iterator over all the elements of the array.
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [11]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


a = np.arange(30): creats a 1D array with 30 values (0 to 29).

b = a.reshape((2, 3, -1)): rearranges the 30 elments in the 1D array "a" to a new shape which is a 3D arrays. So, "b" has three axes (2, 3, -1) which means 2 layers(blocks), and in each layer(block) there are 3 rows. By using -1, we ask numPy to automaticaaly determine the number of the columns (or the last dimension). NumPy calculate the number of columns using the information provided. In our example, by considering the number of elements in the array(30), and the numbers of blocks (2) and rows(3): the number of columns= 30/(2*3) = 5

 So, we will have 5 columns in the array b. So, b = a.reshape((2, 3, -1)) and b = a.reshape((2, 3, 5)) are identical.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [141]:
# Matrix addition according to broadcasting rules:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
#print(f"m1:\n{m1}")
#print(f"m2:\n{m2}")
#print()
print(f"m1 + m2:\n {m1 + m2}")

m1 + m2:
 [[2 3]
 [4 5]]


In [140]:
# Matrix addition according to linear algebra:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
#print(f'm1 shape is: {m1.shape}')
#print(f'm2 shape is: {m2.shape}')
if m1.shape ==  m2.shape:
    print('Adding is possible! The matrices have the same size.')
    print(m1 + m2)
else:
    print('Cannot add matrices, the matrices do not have the same size.')             
              

Cannot add matrices, the matrices do not have the same size.


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [28]:
# Matrix addition according to broadcasting rules:
v1 = np.array([1, 2, 3])
print(f"v1: {v1}")
print(f"v1 + 1: {v1 + 1}")

v1: [1 2 3]
v1 + 1: [2 3 4]


In [37]:
# Matrix addition according to broadcasting rules:
A = np.arange(1, 5).reshape(2,2)
print(f"A: \n{A}")

b = np.array([2, 2])
print(f"b: \n{b}")
print()
print(f"A + b: \n{A + b}")

A: 
[[1 2]
 [3 4]]
b: 
[2 2]

A + b: 
[[3 4]
 [5 6]]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [263]:
# Creating a function with three arguments:

def add_mult_matrices(matrix_1, matrix_2, operator): 
    # Validating that the first two inputs are of type of numpy.ndarray.
    if not isinstance(matrix_1, np.ndarray) and isinstance(matrix_2, np.ndarray):
        raise ValueError("both input must be of type of numpy.ndarray.")
    
    # Validating that the third input is either "add" or "multiply"
    if operator not in ["add", "multiply"]:
        raise ValueError('Choose either "add" or "multiply".') 
           
    # Matrix addition according to linear algebra:
    if operator == "add":
        if matrix_1.shape ==  matrix_2.shape:
            # print('Adding is possible! The matrices have the same size.')
            return matrix_1 + matrix_2
        else:
            raise ValueError('Cannot add matrices, the matrices do not have the same size.')
        
    # Matrix multiplication according to linear algebra:    
    elif operator == "multiply": 
        if matrix_1.shape[1] == matrix_2.shape[0]:
            # print('Multiplication is possible! The column number of matrix_1 is equal to the row number of matrix_2.')
            return matrix_1 @ matrix_2 
        else:
            raise ValueError('Cannot multiply matrices, the column number of matrix_1 is not equal to the row number of matrix_2.')
   

In [170]:
add_mult_matrices(m1, A, "add")

array([[2, 4],
       [6, 8]])

In [171]:
add_mult_matrices(m1, A, "multiply")

array([[ 7, 10],
       [15, 22]])

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [224]:
# Uppgift 10.1.1
x = np.array([4, 3])
print(f"x = {x}")

# Dimension of x
print(f"Dimension of x: {x.ndim}")

# Beräkna 5x and 3x
result_1 = 5 * x
print(f"5x = {result_1}")
result_2 = 3 * x
print(f"3x = {result_2}")

# Beräkna 5x + 3x
print(f'5x + 3x = {add_mult_matrices(result_1, result_2, "add")}')

# Beräkna 8x 
print(f"8x = {8 * x}")

# Beräkna 4x - x
#print(f"4x = {4 * x}")
print(f"4x - x = {(4 * x) - x}")

# Beräkna x^T, vilken blir nya dimension efter att transponeringen utförts?
# x is a 1D vektor and if we use (.T) in numpy to transport it, the result will be the same:
x_T = x.T
print(f"x = {x} and x^T = {x.T}. There is no difference.")
# So, first we need to reshape 1D x to a row-vector:
row_x = x.reshape(1, -1)
print(f"row_x = {row_x}")
# Now, we can use (.T) to transport row_x to a column_x
column_x = row_x.T
print(f"column_x = {column_x}")

# Är x + x^T definierat?
# print(f'x + x^T = {add_mult_matrices(row_x, column_x, "add")}') 
# When I run the code, I get "ValueError: Cannot add matrices, the matrices do not have the same size."
print("Är x + x^T definierat? nej")

# Beräkna ||x||
norm_x = np.linalg.norm(x)
print(f"The norm of x: {norm_x}")

x = [4 3]
Dimension of x: 1
5x = [20 15]
3x = [12  9]
5x + 3x = [32 24]
8x = [32 24]
4x - x = [12  9]
x = [4 3] and x^T = [4 3]. There is no difference.
row_x = [[4 3]]
column_x = [[4]
 [3]]
Är x + x^T definierat? nej
The norm of x: 5.0


In [242]:
# Uppgift 10.1.2
v = np.array([3, 7, 0, 11]).reshape(-1, 1)
print(f"v = \n{v}")

# Dimension of v
print(f"Dimension of v: {v.ndim}")
#print(f"shape of v: {v.shape}")

# Beräkna 2v:
result_v_1 = 2 * v
print(f"2v = \n{result_v_1}")

# Beräkna 5v + 2v
result_v_2 = 5 * v
#print(f"5v = \n{result_v_2}")
print(f'5v + 2v = \n{add_mult_matrices(result_v_2, result_v_1, "add")}')

# Beräkna 4v - 2v
result_v_3 = 4 * v
#print(f"4v = \n{result_v_3}")
if result_v_3.shape == result_v_1.shape:
    print(f"4v - 2v = \n{result_v_3 - result_v_1}")
else:
    print("4v - 2v är inte deinierat")
    
# Beräkna v^T, vilken blir nya dimension efter att transponeringen utförts?
v_T = v.T
print(f"v^T = {v.T}")

# Beräkna ||v||
norm_v = np.linalg.norm(v)
print(f"The norm of v: {norm_v}")

v = 
[[ 3]
 [ 7]
 [ 0]
 [11]]
Dimension of v: 2
2v = 
[[ 6]
 [14]
 [ 0]
 [22]]
5v + 2v = 
[[21]
 [49]
 [ 0]
 [77]]
4v - 2v = 
[[ 6]
 [14]
 [ 0]
 [22]]
v^T = [[ 3  7  0 11]]
The norm of v: 13.379088160259652


In [250]:
# Uppgift 10.1.3
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])
print(f"v1 = {v1} and v2 = {v2}")

# Beräkna ||v1||
norm_v1 = np.linalg.norm(v1)
print(f"The norm of v1: {norm_v1}")

# Beräkna ||v1 - v2||
# Vi börjar med att utföra vektorsubtraktion
vektor_subtraktion = v1 - v2 
#print(f"v1 - v2 = {vektor_subtraktion}")
# Nu beräknar vi normen
norm_vektor_subtraktion = np.linalg.norm(vektor_subtraktion)
print(f"The norm of v1 - v2: {norm_vektor_subtraktion}")


v1 = [4 3 1 5] and v2 = [2 3 1 1]
The norm of v1: 7.14142842854285
The norm of v1 - v2: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [257]:
# Uppgift 10.2.1
# Definiera matriserna:
A = np.array([(2, 1, -1), (1, -1, 1)]).reshape(2, 3)
print(f"A = \n{A}")
B = np.array([(4, -2, 1), (2, -4, -2)]).reshape(2, 3)
print(f"B = \n{B}")
C = np.array([(1, 2), (2, 1)]).reshape(2, 2)
print(f"C = \n{C}")
D = np.array([(3, 4), (4, 3)]).reshape(2, 2)
print(f"D = \n{D}")
E = np.array([(1, 2)]).reshape(2, 1)
print(f"E = \n{E}")
I = np.array([(1, 0), (0, 1)]).reshape(2, 2)
print(f"I = \n{I}")

A = 
[[ 2  1 -1]
 [ 1 -1  1]]
B = 
[[ 4 -2  1]
 [ 2 -4 -2]]
C = 
[[1 2]
 [2 1]]
D = 
[[3 4]
 [4 3]]
E = 
[[1]
 [2]]
I = 
[[1 0]
 [0 1]]


In [289]:
# Uppgift 10.2.1
# 2A
result_2A = 2 * A
print(f"2A = \n{result_2A}")

# I create a simple function called "subt_matrices" to do subtractions according to linear algebra:
def subt_matrices(matrix_1, matrix_2):
    if matrix_1.shape ==  matrix_2.shape:
            return matrix_1 - matrix_2
    else:
            return "Det är inte definierat. Matriserna har inte samma dimention."
        

# B - 2A 
print(f"B - 2A = \n{subt_matrices(B, result_2A)}")

# 3C - 2E
result_3C = 3 * C
result_2E = 2 * E
print(f"3C - 2E = \n{subt_matrices(result_3C , result_2E)}")

# 2D - 3C
result_2D = 2 * D
print(f"2D - 3C = \n{subt_matrices(result_2D , result_3C)}")

# D^T + 2D
D_T = D.T
#print(f"D^T = \n{D.T}")
print(f'D^T + 2D = \n{add_mult_matrices(D_T, result_2D, "add")}')

# 2C^T - 2D^T
result_2C_T = 2 * (C.T)
result_2D_T = 2 * (D.T)
print(f"2C^T - 2D^T = \n{subt_matrices(result_2C_T , result_2D_T)}")

# A^T - B
result_A_T = A.T
print(f"A^T - B = \n{subt_matrices(result_A_T , B)}")

# AC
# by print(f'AC = \n{add_mult_matrices(A, C, "multiply")}'), I got an error.
# ValueError: Cannot multiply matrices, the column number of matrix_1 is not equal to the row number of matrix_2.

# CD
print(f'CD = \n{add_mult_matrices(C, D, "multiply")}')

# CB
print(f'CB = \n{add_mult_matrices(C, B, "multiply")}')

# CI
print(f'CI = \n{add_mult_matrices(C, I, "multiply")}')

# AB^T
result_B_T = B.T
print(f'AB^T = \n{add_mult_matrices(A, result_B_T, "multiply")}')
    

2A = 
[[ 4  2 -2]
 [ 2 -2  2]]
B - 2A = 
[[ 0 -4  3]
 [ 0 -2 -4]]
3C - 2E = 
Det är inte definierat. Matriserna har inte samma dimention.
2D - 3C = 
[[3 2]
 [2 3]]
D^T + 2D = 
[[ 9 12]
 [12  9]]
2C^T - 2D^T = 
[[-4 -4]
 [-4 -4]]
A^T - B = 
Det är inte definierat. Matriserna har inte samma dimention.
CD = 
[[11 10]
 [10 11]]
CB = 
[[  8 -10  -3]
 [ 10  -8   0]]
CI = 
[[1 2]
 [2 1]]
AB^T = 
[[5 2]
 [7 4]]


In [291]:
# Uppgift 10.2.2
# Definiera matrisen:
A = np.array([(2, 3, 4), (5, 4, 1)]).reshape(2, 3)
print(f"A = \n{A}")

# Beräkna AA^T
A_T = A.T
print(f'AA^T = \n{add_mult_matrices(A, A_T, "multiply")}')


A = 
[[2 3 4]
 [5 4 1]]
AA^T = 
[[29 26]
 [26 42]]


In [300]:
# Uppgift 10.2.2
# Definiera matriserna:
A = np.array([(1, 2), (2, 4)]).reshape(2, 2)
print(f"A = \n{A}")
B = np.array([(2, 1), (1, 3)]).reshape(2, 2)
print(f"B = \n{B}")
C = np.array([(4, 3), (0, 2)]).reshape(2, 2)
print(f"C = \n{C}")

# AB
AB = add_mult_matrices(A, B, "multiply")
print(f'AB = \n{AB}')

# AC
AC = add_mult_matrices(A, C, "multiply")
print(f'AC = \n{AC}')

#Verifera att AB = AC
AB == AC


A = 
[[1 2]
 [2 4]]
B = 
[[2 1]
 [1 3]]
C = 
[[4 3]
 [0 2]]
AB = 
[[ 4  7]
 [ 8 14]]
AC = 
[[ 4  7]
 [ 8 14]]


array([[ True,  True],
       [ True,  True]])

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [313]:
v1 = np.arange(4)
v2 = v1[-2:]
print(f"v1 = {v1}")
print(f"v2 = {v2}")
# We can tell if an array is a view or a copy by using the .base attribute
# The base attribute of a view returns the original array while it returns None for a copy.
v2.base # since "v2.base" returns the original array (v1), we can tell that v2 is a view.

v1 = [0 1 2 3]
v2 = [2 3]


array([0, 1, 2, 3])

In [316]:
# we change the last elent of v2 to 123 and print v2
v2[-1] = 123
print(f"v2 = {v2}")
# We can print v1 to check if the last element has changed too or not
print(f"v1 = {v1}") 
# We see the last element of v1 is the same, 123. Since, the original array (v1) & view(v2) share the same memory. 
# So, by changing elements in view, we diectly change the elements of the original array.

v2 = [  2 123]
v1 = [  0   1   2 123]


In [221]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [222]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
